import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="w-full max-w-md mx-auto p-4 h-screen max-h-screen flex flex-col overflow-hidden">
          <Image
            src={"/instarizz.svg"}
            width={103}
            height={28}
            alt="InstaRizz"
          />
          {children}
        </div>
      </body>
    </html>
  );
}
